server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/animal_hospital?serverTimezone=Asia/Seoul
    username: root
    password: lms*!$Ms0828
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 409b3fb04dd78999f86c8dbc4a19372a  # 카카오 REST API 키
            client-secret: hCjNC6r9e9w8N6an8eOBxiWu2ZXP5en0
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8081/oauth/kakao/callback"
            scope: profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      fail-on-empty-beans: 'false'

  application:
    name: animal_hospital_review

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true

jwt:
  secret: AAAABBBBCCCCDDDDEEEEFFFFGGGG123!@#

